# Default values for nginx-argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: nginx-endpoint

replicaCount: 1

image:
  repository: glaceroy/nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.2

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  name: nginx-sa

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 64Mi

volumeMounts:
- name: nginx-tls
  mountPath: /etc/nginx/certs
  readOnly: true

volumes:
- name: nginx-tls
  secret:
    defaultMode: 420
    secretName: nginx-tls