apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-argocd.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-argocd.labels" . | nindent 4 }}
spec:
  ports:
  {{- range .Values.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "nginx-argocd.selectorLabels" . | nindent 4 }}